module:
  hugoVersion:
    min: "0.61.0"
  mounts:
    - source: layouts
      target: layouts
    - source: partials
      target: layouts/partials/tnd-redirects
    - source: console
      target: layouts/partials/tnd-redirects
  imports:
    - path: github.com/theNewDynamic/hugo-module-tnd-console
 
mediaTypes:
  text/netlify:
    delimiter: ''
    suffixes:
      - ''

outputFormats:
  tnd_redirects_netlify:
    baseName: _redirects
    isPlainText: true
    mediatype: text/netlify
    notAlternative: true