module:
  hugoVersion:
    min: "0.61.0"
  mounts:
    - source: layouts
      target: layouts
 
mediaTypes:
  text/netlify:
    delimiter: ''
    suffixes:
      - ''

outputFormats:
  netlify_redir:
    baseName: _redirects
    isPlainText: true
    mediatype: text/netlify
    notAlternative: true